### ISSUE TITLE
weights for propensity 'matching'

### ISSUE THREAD

**Issue by dewittpe** [dewittpe/pstools#1]
Implement and name five weighting methods within `propensity`

| Method | Treated | Control |
| --- | --- | --- |
| IPW, average causal effect in study population | 1/pi | 1/(1-pi) |
| Ave causal effect in treated | 1 | pi/(1-pi) |
| Ave causal effect in untreated | (1-pi)/pi | 1 |
| Ave causal effect in population for which sample is most informative | 1-pi | pi |
| Ave causal effect in matching weight population | min(pi,(1-pi))/pi | min(pi,(1-pi))/(1-pi) |

**Comment by tdbennett** [comment]
These weights are now implemented near the bottom of `icppaper/propensity.R`

**Comment by dewittpe** [comment]
These weights have been implemented in `psweights.R`.
